### ISSUE TITLE
[Bug] Python端无法正常获取到token的值

### ISSUE THREAD

**Issue by ghost** [SaltWood-Studio/Open93AtHome#1]
连接93的服务器可以正常上线

连接93@home就会在获取token时卡住

`[2024-07-15 16:14:02] [INFO] [core.cluster:fetch:43]: 正在获取 token……`

**Comment by SALTWOOD** [comment]
似乎修不了（？

**Comment by SALTWOOD** [comment]
我去问问2b2t

**Comment by tianxiu2b2t** [comment]
提供一下日志啊哥

**Comment by tianxiu2b2t** [comment]
@SALTWOOD 
![image](https://github.com/user-attachments/assets/60c4af59-b8e6-4f68-82e3-bd215c8a6d7f)
您的Content-Type丢哪了？？？

<CIMultiDictProxy('Server': 'nginx/1.24.0 (Ubuntu)', 'Date': 'Mon, 15 Jul 2024 14:55:18 GMT', 'Content-Length': '387', 'Connection': 'keep-alive')>
Traceback (most recent call last):
  File "D:\Desktop_\openbmclapi\core\cluster.py", line 65, in fetch
    json = await resp.json()
           ^^^^^^^^^^^^^^^^^
  File "c:\Users\2b2ttianxiu\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1105, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://saltwood.top:9393/openbmclapi-agent/token')

**Comment by SALTWOOD** [comment]
修了
